name: build

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.10.0
      - name: install
        run: |
          npm i
      - name: bootstrap
        run: |
          npm run bootstrap
      - name: build
        run: |
          npm run build
      - name: test
        run: |
          npm run test
